version: '2'

services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
