version: '2'

services:
  mysql:
    image: mysql:5.7.22
    container_name: memoq-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:5.0.0
    container_name: memoq-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
