apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  labels:
    app: {{ template "backend.name" . }}
    chart: {{ template "backend.chart" . }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "backend.name" . }}
          servicePort: {{ .Values.service.port }}
