apiVersion: v1
kind: Service
metadata:
  name: {{ template "backend-proxy.name" . }}
  labels:
    app: {{ template "backend-proxy.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
  {{- range .Values.sqlproxy.instances }}
  - name: {{ .instance }}
    protocol: TCP
    port: {{ .port }}
    targetPort: {{ .instanceShortName | default (.instance | trunc 15) }}
  {{- end }}
  selector:
    app: {{ template "backend-proxy.name" . }}
